### ISSUE TITLE
StatusBar.setBarStyle is not a function

### ISSUE THREAD

**Issue by horsekitlin** [react-native-fellowship/react-native-navbar#147]
I upgrade from 1.1.7 to 1.3.0 then got this Error screen.

[#d8d0f2332dc6442a6cab5fa6ec8bc377f1e153a5](https://github.com/react-native-fellowship/react-native-navbar/commit/d8d0f2332dc6442a6cab5fa6ec8bc377f1e153a5)

    console.log(StatusBar.setBarStyle) // got undefined

**Comment by gm758** [comment]
I've had the same issue. Arose this morning.

**Comment by Kureev** [comment]
Fixed in `1.3.1`

**Comment by gm758** [comment]
I installed 1.3.1 directly from github, and I'm still getting an error.

StatusBar.barStyle is not a function

**Comment by Kureev** [comment]
@gm758 it requires react-native 0.21+. If you're using previous versions, please, downgrade to `navbar@1.2`

**Comment by damathryx** [comment]
hi. i solved this by changing

`StatusBar.setBarStyle(data.style); `
to 
`StatusBar.barStyle = data.style;`

in node_modules/react-natinve-navbar/ index.js

might work for you too.
